### PR TITLE
Fixed typing to be compatible with latest Storeon

### PR DESCRIPTION
**Pull request by L2jLiga**

### CODE REVIEW

**Comment by ai** [comment]
You can also move this module to [`dual-publish`](https://github.com/ai/dual-publish/) and named export (maybe outside of this PR)

**Comment by L2jLiga** [comment]
Of course, l can do it tomorrow

**Comment by L2jLiga** [comment]
Ok, I think I will finish it in other PR soon

**Comment by ivan-solovev** [comment]
I am closing this PR, because it is not relevant. Thank you for the PR #12.

**Pull request closed without merging**
